# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "C:/Program Files/CMake/bin/cmake.exe"

# The command to remove a file.
RM = "C:/Program Files/CMake/bin/cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:/Users/plane/OneDrive/Documents/GitHub/2D-physics-engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:/Users/plane/OneDrive/Documents/GitHub/2D-physics-engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:/Program Files/CMake/bin/cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:/Program Files/CMake/bin/cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Users/plane/OneDrive/Documents/GitHub/2D-physics-engine/CMakeFiles C:/Users/plane/OneDrive/Documents/GitHub/2D-physics-engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:/Users/plane/OneDrive/Documents/GitHub/2D-physics-engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Engine

# Build rule for target.
Engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Engine
.PHONY : Engine

# fast build rule for target.
Engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/build
.PHONY : Engine/fast

#=============================================================================
# Target rules for targets named Glad

# Build rule for target.
Glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Glad
.PHONY : Glad

# fast build rule for target.
Glad/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glad.dir/build.make CMakeFiles/Glad.dir/build
.PHONY : Glad/fast

#=============================================================================
# Target rules for targets named Engine_files

# Build rule for target.
Engine_files: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Engine_files
.PHONY : Engine_files

# fast build rule for target.
Engine_files/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/build
.PHONY : Engine_files/fast

src/client_main.obj: src/client_main.cpp.obj
.PHONY : src/client_main.obj

# target to build an object file
src/client_main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/client_main.cpp.obj
.PHONY : src/client_main.cpp.obj

src/client_main.i: src/client_main.cpp.i
.PHONY : src/client_main.i

# target to preprocess a source file
src/client_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/client_main.cpp.i
.PHONY : src/client_main.cpp.i

src/client_main.s: src/client_main.cpp.s
.PHONY : src/client_main.s

# target to generate assembly for a file
src/client_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine.dir/build.make CMakeFiles/Engine.dir/src/client_main.cpp.s
.PHONY : src/client_main.cpp.s

src/core.obj: src/core.cpp.obj
.PHONY : src/core.obj

# target to build an object file
src/core.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/core.cpp.obj
.PHONY : src/core.cpp.obj

src/core.i: src/core.cpp.i
.PHONY : src/core.i

# target to preprocess a source file
src/core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/core.cpp.i
.PHONY : src/core.cpp.i

src/core.s: src/core.cpp.s
.PHONY : src/core.s

# target to generate assembly for a file
src/core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/core.cpp.s
.PHONY : src/core.cpp.s

src/ecs.obj: src/ecs.cpp.obj
.PHONY : src/ecs.obj

# target to build an object file
src/ecs.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/ecs.cpp.obj
.PHONY : src/ecs.cpp.obj

src/ecs.i: src/ecs.cpp.i
.PHONY : src/ecs.i

# target to preprocess a source file
src/ecs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/ecs.cpp.i
.PHONY : src/ecs.cpp.i

src/ecs.s: src/ecs.cpp.s
.PHONY : src/ecs.s

# target to generate assembly for a file
src/ecs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/ecs.cpp.s
.PHONY : src/ecs.cpp.s

src/erosion.obj: src/erosion.cpp.obj
.PHONY : src/erosion.obj

# target to build an object file
src/erosion.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/erosion.cpp.obj
.PHONY : src/erosion.cpp.obj

src/erosion.i: src/erosion.cpp.i
.PHONY : src/erosion.i

# target to preprocess a source file
src/erosion.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/erosion.cpp.i
.PHONY : src/erosion.cpp.i

src/erosion.s: src/erosion.cpp.s
.PHONY : src/erosion.s

# target to generate assembly for a file
src/erosion.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/erosion.cpp.s
.PHONY : src/erosion.cpp.s

src/glad.obj: src/glad.c.obj
.PHONY : src/glad.obj

# target to build an object file
src/glad.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glad.dir/build.make CMakeFiles/Glad.dir/src/glad.c.obj
.PHONY : src/glad.c.obj

src/glad.i: src/glad.c.i
.PHONY : src/glad.i

# target to preprocess a source file
src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glad.dir/build.make CMakeFiles/Glad.dir/src/glad.c.i
.PHONY : src/glad.c.i

src/glad.s: src/glad.c.s
.PHONY : src/glad.s

# target to generate assembly for a file
src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glad.dir/build.make CMakeFiles/Glad.dir/src/glad.c.s
.PHONY : src/glad.c.s

src/gui.obj: src/gui.cpp.obj
.PHONY : src/gui.obj

# target to build an object file
src/gui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/gui.cpp.obj
.PHONY : src/gui.cpp.obj

src/gui.i: src/gui.cpp.i
.PHONY : src/gui.i

# target to preprocess a source file
src/gui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/gui.cpp.i
.PHONY : src/gui.cpp.i

src/gui.s: src/gui.cpp.s
.PHONY : src/gui.s

# target to generate assembly for a file
src/gui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/gui.cpp.s
.PHONY : src/gui.cpp.s

src/input.obj: src/input.cpp.obj
.PHONY : src/input.obj

# target to build an object file
src/input.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/input.cpp.obj
.PHONY : src/input.cpp.obj

src/input.i: src/input.cpp.i
.PHONY : src/input.i

# target to preprocess a source file
src/input.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/input.cpp.i
.PHONY : src/input.cpp.i

src/input.s: src/input.cpp.s
.PHONY : src/input.s

# target to generate assembly for a file
src/input.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/input.cpp.s
.PHONY : src/input.cpp.s

src/physics.obj: src/physics.cpp.obj
.PHONY : src/physics.obj

# target to build an object file
src/physics.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/physics.cpp.obj
.PHONY : src/physics.cpp.obj

src/physics.i: src/physics.cpp.i
.PHONY : src/physics.i

# target to preprocess a source file
src/physics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/physics.cpp.i
.PHONY : src/physics.cpp.i

src/physics.s: src/physics.cpp.s
.PHONY : src/physics.s

# target to generate assembly for a file
src/physics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/physics.cpp.s
.PHONY : src/physics.cpp.s

src/random.obj: src/random.cpp.obj
.PHONY : src/random.obj

# target to build an object file
src/random.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/random.cpp.obj
.PHONY : src/random.cpp.obj

src/random.i: src/random.cpp.i
.PHONY : src/random.i

# target to preprocess a source file
src/random.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/random.cpp.i
.PHONY : src/random.cpp.i

src/random.s: src/random.cpp.s
.PHONY : src/random.s

# target to generate assembly for a file
src/random.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/random.cpp.s
.PHONY : src/random.cpp.s

src/render.obj: src/render.cpp.obj
.PHONY : src/render.obj

# target to build an object file
src/render.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/render.cpp.obj
.PHONY : src/render.cpp.obj

src/render.i: src/render.cpp.i
.PHONY : src/render.i

# target to preprocess a source file
src/render.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/render.cpp.i
.PHONY : src/render.cpp.i

src/render.s: src/render.cpp.s
.PHONY : src/render.s

# target to generate assembly for a file
src/render.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/render.cpp.s
.PHONY : src/render.cpp.s

src/wrapper.obj: src/wrapper.cpp.obj
.PHONY : src/wrapper.obj

# target to build an object file
src/wrapper.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/wrapper.cpp.obj
.PHONY : src/wrapper.cpp.obj

src/wrapper.i: src/wrapper.cpp.i
.PHONY : src/wrapper.i

# target to preprocess a source file
src/wrapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/wrapper.cpp.i
.PHONY : src/wrapper.cpp.i

src/wrapper.s: src/wrapper.cpp.s
.PHONY : src/wrapper.s

# target to generate assembly for a file
src/wrapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Engine_files.dir/build.make CMakeFiles/Engine_files.dir/src/wrapper.cpp.s
.PHONY : src/wrapper.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Engine"
	@echo "... Engine_files"
	@echo "... Glad"
	@echo "... src/client_main.obj"
	@echo "... src/client_main.i"
	@echo "... src/client_main.s"
	@echo "... src/core.obj"
	@echo "... src/core.i"
	@echo "... src/core.s"
	@echo "... src/ecs.obj"
	@echo "... src/ecs.i"
	@echo "... src/ecs.s"
	@echo "... src/erosion.obj"
	@echo "... src/erosion.i"
	@echo "... src/erosion.s"
	@echo "... src/glad.obj"
	@echo "... src/glad.i"
	@echo "... src/glad.s"
	@echo "... src/gui.obj"
	@echo "... src/gui.i"
	@echo "... src/gui.s"
	@echo "... src/input.obj"
	@echo "... src/input.i"
	@echo "... src/input.s"
	@echo "... src/physics.obj"
	@echo "... src/physics.i"
	@echo "... src/physics.s"
	@echo "... src/random.obj"
	@echo "... src/random.i"
	@echo "... src/random.s"
	@echo "... src/render.obj"
	@echo "... src/render.i"
	@echo "... src/render.s"
	@echo "... src/wrapper.obj"
	@echo "... src/wrapper.i"
	@echo "... src/wrapper.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

